---
- name: Remove  site-avaibles and sites-enabled
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled
  ignore_errors: yes

- name: Override nginx.conf
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"

- name: Configure external nginx configuration
  copy:
    src: "{{ vhost_directory}}"
    dest: "/etc/nginx/conf.d/"
  notify:
    - validate nginx
    - reload nginx

- name: force all notified handlers to run
  meta: flush_handlers
